### ISSUE TITLE
What is the use of solana source code?

### ISSUE THREAD

**Issue by alex4506** [rpcpool/solana-rpc-ansible#7]
Hi, this is an amazing project and I am working on using ansible-lint to format it, but I wonder what is this for?

https://github.com/rpcpool/solana-rpc-ansible/blob/7861b9237fae3870c7e78bf234627d7627f3870e/tasks/install.yml#L36

**Comment by alex4506** [comment]
And another question is why should we install rust?

**Comment by Lusitaniae** [comment]
The role is installing the Solana validator from source code, so it will checkout the repo and build it using rust/cargo
